import { expect, test } from '@playwright/test'

test('complete private and public note lifecycle', async ({ page, browser }) => {
  const email = `e2e-${Date.now()}@example.test`
  await page.goto('/register')
  await page.getByLabel('Имя').fill('E2E User')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Пароль').fill('strong-test-password')
  await page.getByRole('button', { name: 'Зарегистрироваться' }).click()
  await expect(page.getByRole('heading', { name: 'Записные книжки' })).toBeVisible()
  await expect(page.getByText('E2E User')).toBeVisible()
  await expect(page.getByText(email)).toBeVisible()

  await page.getByRole('button', { name: 'Создать записную книжку' }).click()
  await expect(page.getByRole('heading', { name: 'Новая записная книжка' })).toBeVisible()
  await page.getByRole('button', { name: 'Переименовать' }).click()
  await page.getByLabel('Новое название книжки').fill('Исследования')
  await page.getByRole('button', { name: 'Сохранить название' }).click()
  await page.getByRole('button', { name: 'Создать заметку' }).click()
  await page.getByLabel('Название').fill('Первая заметка')
  await page.getByLabel('Markdown').fill('# Привет\n\n**Безопасный текст**\n\n<script>alert(1)</script>')
  await expect(page.getByRole('navigation', { name: 'Путь к заметке' })).toContainText('Исследования')
  await expect(page.getByRole('navigation', { name: 'Путь к заметке' })).toContainText('Первая заметка')
  await expect(page.getByText('Есть изменения')).toBeVisible()
  await page.getByRole('button', { name: 'Сохранить' }).click()
  await expect(page.getByText('Сохранено')).toBeVisible({ timeout: 5_000 })
  await expect(page.locator('.preview')).toContainText('Безопасный текст')
  await expect(page.locator('.preview script')).toHaveCount(0)
  await page.reload()
  await expect(page.getByLabel('Markdown')).toContainText('Безопасный текст')

  const search = page.getByRole('searchbox', { name: 'Поиск заметок' })
  const searchResponse = page.waitForResponse(response => response.url().includes('/api/v1/notes/search?q='))
  await search.fill('Безопасный')
  await expect(search).toHaveAttribute('aria-expanded', 'true')
  expect((await searchResponse).ok()).toBe(true)
  const suggestion = page.getByRole('option', { name: /Первая заметка/ })
  await expect(suggestion).toBeVisible()
  await expect(suggestion.locator('mark')).toHaveText('Безопасный')
  await search.press('Escape')

  await page.getByRole('button', { name: 'Поделиться' }).click()
  const publicUrl = await page.getByRole('status').getByRole('link', { name: 'открыть' }).getAttribute('href')
  expect(publicUrl).toBeTruthy()
  const anonymous = await browser.newContext()
  const publicPage = await anonymous.newPage()
  await publicPage.goto(publicUrl!)
  await expect(publicPage.getByText('Только чтение')).toBeVisible()
  await expect(publicPage.getByText('Безопасный текст')).toBeVisible()
  await expect(publicPage.locator('textarea')).toHaveCount(0)
  await page.getByRole('button', { name: 'Отключить ссылку' }).click()
  await expect(page.getByRole('button', { name: 'Поделиться' })).toBeVisible()
  await publicPage.reload()
  await expect(publicPage.getByRole('heading', { name: 'Заметка недоступна' })).toBeVisible()
  await anonymous.close()
})
