import { expect, test } from '@playwright/test'

test('complete private and public note lifecycle', async ({ page, browser }) => {
  const email = `e2e-${Date.now()}@example.test`
  await page.goto('/register')
  await page.getByLabel('Имя').fill('E2E User')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Пароль').fill('strong-test-password')
  await page.getByRole('button', { name: 'Зарегистрироваться' }).click()
  await expect(page.getByRole('heading', { name: 'Записные книжки' })).toBeVisible()

  await page.getByLabel('Название книжки').fill('Исследования')
  await page.getByRole('button', { name: 'Создать' }).click()
  await page.getByRole('link', { name: /Исследования/ }).click()
  await page.getByLabel('Название заметки').fill('Первая заметка')
  await page.getByRole('button', { name: 'Создать заметку' }).click()
  await page.getByLabel('Markdown').fill('# Привет\n\n**Безопасный текст**\n\n<script>alert(1)</script>')
  await expect(page.getByText('Есть изменения')).toBeVisible()
  await page.getByRole('button', { name: 'Сохранить' }).click()
  await expect(page.getByText('Сохранено')).toBeVisible({ timeout: 5_000 })
  await expect(page.locator('.preview')).toContainText('Безопасный текст')
  await expect(page.locator('.preview script')).toHaveCount(0)
  await page.reload()
  await expect(page.getByLabel('Markdown')).toContainText('Безопасный текст')

  await page.getByRole('button', { name: 'Поделиться' }).click()
  const publicUrl = await page.getByRole('status').getByRole('link', { name: 'открыть' }).getAttribute('href')
  expect(publicUrl).toBeTruthy()
  const anonymous = await browser.newContext()
  const publicPage = await anonymous.newPage()
  await publicPage.goto(publicUrl!)
  await expect(publicPage.getByText('Только чтение')).toBeVisible()
  await expect(publicPage.getByText('Безопасный текст')).toBeVisible()
  await expect(publicPage.locator('textarea')).toHaveCount(0)
  await page.getByRole('button', { name: 'Отключить ссылку' }).click()
  await publicPage.reload()
  await expect(publicPage.getByRole('heading', { name: 'Заметка недоступна' })).toBeVisible()
  await anonymous.close()
})
